export const FETCH_INVENTORY = 'FETCH_INVENTORY';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';

export const CREATE_SPACE = 'CREATE_SPACE';
export const CREATE_SPACE_SUCCESS = 'CREATE_SPACE_SUCCESS';
export const CREATE_SPACE_FAILURE = 'CREATE_SPACE_FAILURE';
