export const GET_MATCHES = 'GET_MATCHES';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAILURE = 'GET_MATCHES_FAILURE';

export const GET_TODAYS_MATCHES = 'GET_TODAYS_MATCHES';
export const GET_TODAYS_MATCHES_SUCCESS = 'GET_TODAYS_MATCHES_SUCCESS';
export const GET_TODAYS_MATCHES_FAILURE = 'GET_TODAYS_MATCHES_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

/** Start workout constants */
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const CREATE_WORKOUT_FAILURE = 'CREATE_WORKOUT_FAILURE';

export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETCH_WORKOUTS_FAILURE = 'FETCH_WORKOUTS_FAILURE';

export const FETCH_WORKOUT = 'FETCH_WORKOUT';
export const FETCH_WORKOUT_SUCCESS = 'FETCH_WORKOUT_SUCCESS';
export const FETCH_WORKOUT_FAILURE = 'FETCH_WORKOUT_FAILURE';

export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const UPDATE_WORKOUT_SUCCESS = 'UPDATE_WORKOUT_SUCCESS';
export const UPDATE_WORKOUT_FAILURE = 'UPDATE_WORKOUT_FAILURE';
/** End workout constants */

/** Start exercise constants */
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'CREATE_EXERCISE_FAILURE';

export const FETCH_EXERCISE = 'FETCH_EXERCISE';
export const FETCH_EXERCISE_SUCCESS = 'FETCH_EXERCISE_SUCCESS';
export const FETCH_EXERCISE_FAILURE = 'FETCH_EXERCISE_FAILURE';

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';
/** End exercise constants */

/** Start SET constants */
export const CREATE_SET = 'CREATE_SET';
export const CREATE_SET_SUCCESS = 'CREATE_SET_SUCCESS';
export const CREATE_SET_FAILURE = 'CREATE_SET_FAILURE';

export const DELETE_SET = 'DELETE_SET';
export const DELETE_SET_SUCCESS = 'DELETE_SET_SUCCESS';
export const DELETE_SET_FAILURE = 'DELETE_SET_FAILURE';
/** End SET constants */
